containerized emacs

diff --git a/defaults/bin/emx b/defaults/bin/emx
--- a/defaults/bin/emx
+++ b/defaults/bin/emx
@@ -2,16 +2,31 @@
 # -*- mode: shellscript -*-
 set -euo pipefail
 show_help(){
-    echo "Launches an instance of Emacs 29 (master branch)"
+    echo "Launches an instance of emacs (master branch)"
     echo ""
     echo "Usage:"
-    echo "--broadway <display-number>   E.g. 5, then open http://localhost:8085"
-    echo "--use <version>           E.g. 28.doom, symlinks .emcas.d.<version> to /root/.emacs.d"
+    echo "--client                     runs as client"
+    echo "--daemon                     runs as a daemon"
+    echo "--broadway <display-number>  e.g. 5, then open http://localhost:8085"
+    echo "--use <version>              e.g. 28.doom, symlinks .emcas.d.<version> to /root/.emacs.d"
+    echo ""
+    echo "Extra arguments passed to podrun (wrapper around podman) can be specified after a  '--' token."
 }
+declare -a EMACS_ARGS
 USE_EMACS_D=""
 USE_BROADWAY=""
+RUN_AS_DAEMON=0
+RUN_AS_CLIENT=0
 while [ $# -gt 0 ]; do
     case "$1" in
+        --client)
+            RUN_AS_CLIENT=1
+            shift
+            ;;
+        --daemon)
+            RUN_AS_DAEMON=1
+            shift
+            ;;
         --broadway)
             shift
             USE_BROADWAY=$1
@@ -26,12 +41,30 @@ while [ $# -gt 0 ]; do
             show_help
             exit 0
             ;;
+        --)
+            shift
+            for arg in "$@"; do
+                if [[ $arg == "--" ]]; then
+                    >&2 echo "Multiple '--' args will not work with this script."
+                fi
+            done
+            break
+            ;;
         *)
-           show_help
-           exit 1
-           ;;
+            EMACS_ARGS+=("$1")
+            shift
+            # >&2 echo "Unknown argument: $1"
+            # show_help
+            # exit 1
+            # break
+            ;;
     esac
 done
+
+if [[ $RUN_AS_CLIENT == 1 && $RUN_AS_DAEMON == 1 ]]; then
+    >&2 echo "Cannot run as both client and daemon at the same time"
+    exit 1
+fi
 if [ ! -e ~/.emx ]; then
     mkdir ~/.emx
 fi
@@ -53,26 +86,63 @@ set -g remain-on-exit on  # cf. respawn-pane & respawn-pane -k
 set -g history-limit 15000  # default is 2000 lines
 EOF
 
-if [[ $USE_BROADWAY != "" ]]; then
-    BJODAH_ARGS="-p 127.0.0.1:808$USE_BROADWAY:808$USE_BROADWAY"
-    cat <<EOF>~/.emx/launch.sh
-tmux  -2 -S tmux-bjodah.sock -f /emx/.tmux.conf new -s emx "broadwayd :$USE_BROADWAY" \
-    \; new-window "GDK_BACKEND=broadway BROADWAY_DISPLAY=:$USE_BROADWAY /opt/emacs-pgtk-gcc-29/bin/emacs"
-EOF
-    TMUX_ARGS=""
-    xdg-open "http://localhost:8085"
+if [[ $USE_EMACS_D == 28* ]]; then
+    EMACS_PREFIX=/opt/emacs-28
+elif [[ $USE_EMACS_D == 29* ]]; then
+    EMACS_PREFIX=/opt/emacs-pgtk-gcc-29
 else
-    BJODAH_ARGS=""
-    cat <<EOF>~/.emx/launch.sh
-tmux -2 -S tmux-bjodah.sock -f /emx/.tmux.conf new -s emx /opt/emacs-pgtk-gcc-29/bin/emacs
-EOF
-
+    >&2 echo "TODO: implment handling for verion: $USE_EMACS_D"
 fi
 
-bjodah \
-    -v ~/.emx:/emx \
-    -v ~/.emx/.emacs-eln-cache:/root/.emacs.d.29/eln-cache \
-    $BJODAH_ARGS \
-    -- "ln -s /root/.emacs.d.29 /root/.emacs.d && \
+if [[ $RUN_AS_CLIENT == 1 ]]; then
+    # EMACS_BIN="emacsclient -nc -s /emx/emx-server"
+    EMACS_BIN="emacsclient -nc -s emx-server"
+    PODRUN_ARGS="--name emx-client-$(printf '%(%s)T\n' -1)"
+    LAUNCH_COMMAND="$EMACS_PREFIX/bin/$EMACS_BIN ${EMACS_ARGS[@]}"
+else
+    LAUNCH_COMMAND="ln -s /root/.emacs.d.$USE_EMACS_D /root/.emacs.d && \
         bash /opt/bjodah-dotfiles/install_defaults.sh && \
-        set -x; source /emx/launch.sh"
+        set -x; chmod 700 /emx; . /emx/launch.sh"
+    if [[ $RUN_AS_DAEMON == 1 ]]; then
+        if [[ $USE_BROADWAY != "" ]]; then
+            >&2 echo "Cannot combine daemon and broadway"
+            exit 1
+        fi
+#         cat <<EOF>~/.emx/daemon-init.el
+# (progn
+#   (require 'server)
+#   (setq server-socket-dir "/emx")
+#   (setq server-name "emx-server")
+#   (server-start)
+#   (load-file "~/.emacs.d/init.el")
+# )
+# EOF
+#         EMACS_BIN="emacs --eval '(load \"/emx/daemon-init.el\")'"
+        EMACS_BIN="emacs --daemon=emx-server"
+        PODRUN_ARGS="--name emx-daemon"
+    elif [[ $USE_BROADWAY != "" ]]; then
+        PODRUN_ARGS="-p 127.0.0.1:808$USE_BROADWAY:808$USE_BROADWAY $PODRUN_ARGS"
+        cat <<EOF>~/.emx/launch.sh
+tmux  -2 -S tmux-podrun.sock -f /emx/.tmux.conf new -s emx "broadwayd :$USE_BROADWAY" \
+    \; new-window "GDK_BACKEND=broadway BROADWAY_DISPLAY=:$USE_BROADWAY $EMACS_PREFIX/bin/$EMACS_BIN ${EMACS_ARGS[@]}"
+EOF
+        TMUX_ARGS=""
+        xdg-open "http://localhost:808$USE_BROADWAY"
+    else
+        EMACS_BIN=emacs
+        PODRUN_ARGS="--name emx"
+        cat <<EOF>~/.emx/launch.sh
+tmux -2 -S tmux-podrun.sock -f /emx/.tmux.conf new -s emx $EMACS_PREFIX/bin/$EMACS_BIN ${EMACS_ARGS[@]}
+EOF
+    fi
+fi
+
+podrun \
+    -v ~/.emx:/emx \
+    -v ~/.emx/.emacs-eln-cache:/root/.emacs.d.$USE_EMACS_D/eln-cache \
+    -v $XDG_RUNTIME_DIR:$XDG_RUNTIME_DIR \
+    -e XDG_RUNTIME_DIR \
+    --image bjodah/bjodahimg22dot:22.4.a.1.3 \
+    $PODRUN_ARGS \
+    $* \
+    -- $LAUNCH_COMMAND
